import { useState } from "react";
import { ToolIcon, toolLabel } from "../ToolIcon.jsx";

const FILTERS = ["All", "Critical", "High", "Medium"];

const URGENCY_COLOR = {
  critical: "var(--urgency-critical)", high: "var(--urgency-high)",
  medium: "var(--urgency-medium)", low: "var(--urgency-low)",
};
const URGENCY_TINT = {
  critical: "var(--danger-tint)", high: "#ffe9dc",
  medium: "var(--warning-tint)", low: "var(--success-tint)",
};

/**
 * Picks a tool-aware confirmation for the plan item's own suggested_action
 * text (already specific, generated by the reasoning step) - the button
 * label stays exactly what the agent suggested; only the icon and the
 * confirmation phrasing adapt to which connector the item came from.
 */
function confirmFor(sourceTool, suggestedAction) {
  const phrasing = {
    outlook: `Marked done in Outlook: "${suggestedAction}"`,
    teams: `Sent on Teams: "${suggestedAction}"`,
    slack: `Posted on Slack: "${suggestedAction}"`,
    tracker: `Updated in Jira: "${suggestedAction}"`,
  };
  return phrasing[sourceTool] || `Done: "${suggestedAction}"`;
}

export default function PlanCards({ plan, onFeedback, adjusting }) {
  const [hoveredIdx, setHoveredIdx] = useState(null);
  const [filter, setFilter] = useState("All");

  if (!plan || plan.length === 0) {
    return (
      <div style={{ color: "var(--text-tertiary)", fontSize: 13, padding: "32px 0", textAlign: "center" }}>
        Choose a time of day and ask for your plan to see prioritized items here.
      </div>
    );
  }

  const sorted = plan.slice().sort((a, b) => a.rank - b.rank);
  const filtered = filter === "All" ? sorted : sorted.filter((item) => item.urgency?.toLowerCase() === filter.toLowerCase());

  return (
    <div>
      <div style={{ display: "flex", gap: 6, marginBottom: 14 }}>
        {FILTERS.map((f) => {
          const count = f === "All" ? sorted.length : sorted.filter((i) => i.urgency?.toLowerCase() === f.toLowerCase()).length;
          const active = filter === f;
          return (
            <button
              key={f}
              onClick={() => setFilter(f)}
              style={{
                display: "flex", alignItems: "center", gap: 6, fontSize: 12.5, fontWeight: 600,
                padding: "6px 12px", borderRadius: 20, cursor: "pointer",
                border: active ? `1px solid ${f === "All" ? "var(--accent-primary)" : URGENCY_COLOR[f.toLowerCase()]}` : "1px solid var(--border-default)",
                background: active ? (f === "All" ? "var(--accent-primary-tint)" : URGENCY_TINT[f.toLowerCase()]) : "var(--surface-card)",
                color: active ? (f === "All" ? "var(--accent-primary)" : URGENCY_COLOR[f.toLowerCase()]) : "var(--text-secondary)",
              }}
            >
              {f}
              <span style={{
                fontSize: 10.5, fontWeight: 700, background: active ? "rgba(0,0,0,0.12)" : "var(--border-strong)",
                color: active ? "inherit" : "#fff", borderRadius: "50%", width: 18, height: 18,
                display: "inline-flex", alignItems: "center", justifyContent: "center",
              }}>
                {count}
              </span>
            </button>
          );
        })}
      </div>

      {filtered.length === 0 ? (
        <div style={{ color: "var(--text-tertiary)", fontSize: 13, padding: "24px 0", textAlign: "center" }}>
          No {filter.toLowerCase()} priority items right now.
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {filtered.map((item, i) => (
            <PlanCard
              key={`${item.title}-${i}`}
              item={item}
              hovered={hoveredIdx === i}
              onMouseEnter={() => setHoveredIdx(i)}
              onMouseLeave={() => setHoveredIdx(null)}
              onFeedback={onFeedback}
              adjusting={adjusting}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function PlanCard({ item, hovered, onMouseEnter, onMouseLeave, onFeedback, adjusting }) {
  const [noteOpen, setNoteOpen] = useState(false);
  const [note, setNote] = useState("");
  const [confirmation, setConfirmation] = useState(null);

  function handleActionClick() {
    setConfirmation(confirmFor(item.source_tool, item.suggested_action));
    setTimeout(() => setConfirmation(null), 3000);
  }

  return (
    <div
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      style={{
        border: "1px solid var(--border-accent)",
        borderRadius: "var(--radius-md)",
        padding: "14px 16px",
        background: "var(--surface-card)",
        boxShadow: "var(--shadow-sm)",
        opacity: adjusting ? 0.6 : 1,
        transition: "opacity 150ms ease",
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 10 }}>
        <div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
          <div
            style={{
              width: 24, height: 24, borderRadius: "50%", background: "var(--surface-sunken)",
              color: "var(--text-secondary)", fontSize: 12, fontWeight: 700,
              display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0,
            }}
          >
            {item.rank}
          </div>
          <div>
            <div style={{ fontSize: 14.5, fontWeight: 600 }}>{item.title}</div>
            <div style={{ fontSize: 12.5, color: "var(--text-secondary)", marginTop: 3 }}>{item.why}</div>
          </div>
        </div>
        <span
          style={{
            fontSize: 10.5, fontWeight: 700, textTransform: "uppercase",
            color: URGENCY_COLOR[item.urgency] || "var(--text-secondary)",
            background: URGENCY_TINT[item.urgency] || "var(--surface-sunken)",
            padding: "3px 9px", borderRadius: 20, whiteSpace: "nowrap", flexShrink: 0,
          }}
        >
          {item.urgency}
        </span>
      </div>

      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 10, paddingLeft: 34, flexWrap: "wrap", gap: 8 }}>
        <span style={{ fontSize: 11, display: "inline-flex", alignItems: "center", gap: 6, color: "var(--text-tertiary)" }}>
          <ToolIcon tool={item.source_tool} size={15} />
          {toolLabel(item.source_tool)}
        </span>
        <button
          onClick={handleActionClick}
          style={{
            fontSize: 11.5, fontWeight: 600, whiteSpace: "nowrap",
            background: "var(--accent-primary-tint)", color: "var(--accent-primary)",
            border: "1px solid var(--accent-primary)", borderRadius: 20, padding: "5px 12px", cursor: "pointer",
          }}
        >
          {item.suggested_action}
        </button>
      </div>

      {confirmation && (
        <div style={{ fontSize: 12, color: "var(--success)", marginTop: 8, paddingLeft: 34 }}>✓ {confirmation}</div>
      )}

      {/* Human-in-the-loop feedback - only shown on hover so the card list stays clean */}
      {onFeedback && (
        <div style={{ paddingLeft: 34, maxHeight: hovered || noteOpen ? 90 : 0, overflow: "hidden", transition: "all 150ms ease" }}>
          <div style={{ display: "flex", gap: 8, marginTop: 10 }}>
            <button
              disabled={adjusting}
              onClick={() => onFeedback(item.title, "not_relevant", note || null)}
              style={{
                fontSize: 11.5, padding: "4px 10px", borderRadius: 20, cursor: adjusting ? "default" : "pointer",
                border: "1px solid var(--border-strong)", background: "var(--surface-canvas)", color: "var(--text-secondary)",
              }}
            >
              👎 Not relevant
            </button>
            <button
              disabled={adjusting}
              onClick={() => onFeedback(item.title, "prioritize", note || null)}
              style={{
                fontSize: 11.5, padding: "4px 10px", borderRadius: 20, cursor: adjusting ? "default" : "pointer",
                border: "1px solid var(--accent-primary)", background: "var(--accent-primary-tint)", color: "var(--accent-primary)",
              }}
            >
              ⬆ Make this top priority
            </button>
            <button
              onClick={() => setNoteOpen((v) => !v)}
              style={{
                fontSize: 11.5, padding: "4px 10px", borderRadius: 20, cursor: "pointer",
                border: "1px dashed var(--border-strong)", background: "transparent", color: "var(--text-tertiary)",
              }}
            >
              {noteOpen ? "Hide note" : "💬 Add a note"}
            </button>
          </div>
          {noteOpen && (
            <input
              value={note}
              onChange={(e) => setNote(e.target.value)}
              placeholder={`Tell the agent more, e.g. "this is actually due next week"`}
              style={{
                width: "100%", marginTop: 8, padding: "6px 10px", fontSize: 12,
                border: "1px solid var(--border-default)", borderRadius: "var(--radius-md)", outline: "none",
              }}
            />
          )}
        </div>
      )}
    </div>
  );
}
